### ISSUE TITLE
Rudimentary documentation

### ISSUE THREAD

**Issue by ariddell** [sakrejda/protostan#5]
What's the best way to document the proto files and the shim C++ files? It would be nice to automatically generate HTML docs for future interface writers.

**Comment by sakrejda** [comment]
How about this one: https://github.com/estan/protoc-gen-doc/

**Comment by ariddell** [comment]
That looks great.

I suppose we also need to write & generate documentation for the shim
functions.

**Comment by sakrejda** [comment]
Yep, I think using whatever Stan uses for those is fine (doxygen?)

**Comment by sakrejda** [comment]
Ok, close this after we:
- [x] check to make sure we can't just use doxygen comments for documenting proto files.
- [x] add protoc-gen-doc [generator](https://github.com/estan/protoc-gen-doc/) plugin as a submodule 
- [x] document current messages in protoc-gen-doc format
- [ ] add makefile logic to generate documentation for shim files
- [ ] add makefile logic to generate documentation for proto files.

**Comment by sakrejda** [comment]
Had started working on this, didn't realize I didn't claim it.

**Comment by sakrejda** [comment]
Turns out protoc-gen-doc is not straightforward to install from source so I can't just add it as a submodule and make it go.  It relies on qmake to produce the makefile and the qmake project file is hard-coded to look for system libraries.  I'm not going to go through incorporating it into the makefile at this point.  We can follow this format for writing the documentation comments and it'll be easier to install once protobuf-3 is the mainline system protobuf (so in a few to six months (?)).
